### ISSUE TITLE
`Interface: column names`?

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverse/design#146] opened 2023-06-30 23:51 UTC
Something about how we decide when function inputs should be quoted strings vs unquoted tidyselections. It would be nice to have something to point to that describes this (im surprised we dont already!) because we get this question a lot, and it would be good to provide guidance for others who make tidyverse wrappers that take similar kinds of inputs.

See https://fosstodon.org/@jennybryan/110634283789512332 where @jennybc gives our usual advice of:

- unquoted when referring to columns that already exist _(typically through tidyselection)_
- quoted string for columns that do not yet exist _(nowadays type checked by `check_name()` or `check_character()`)_

**Comment by hadley** [comment] 2023-07-20 19:08
Somewhat related: do you want a mutate-style or select-style interface?

**Comment by hadley** [comment] 2023-07-20 20:09
Duplicate of #101

**Closed by hadley** 2023-07-20 20:09 UTC
Labels: interface :gift:
