### ISSUE TITLE
Functions that fabricate or repair column names

### ISSUE THREAD

**Issue by jennybc** [tidyverse/design#34] opened 2018-12-11 16:42 UTC
Inspired by [this list](https://github.com/r-lib/vctrs/blob/491382d3d91c24703af4100c4140fd0ab4bb8249/README.Rmd#L98-L122) made by @Hadley in early [vctrs](https://github.com/r-lib/vctrs) work, regarding type coercion across the tidyverse.

Functions where we create column names out of thin air or from inputs and could / should do so according to common principles. *this list will grow as we stumble across these*

  * `tidyr::spread()`
  * `dplyr::inner_join()` and friends
  * `dplyr::summarise()`
  * `dplyr::mutate()`
  * `tidyr::gather()`
  * `tidyr::unnest()`

**Comment by njtierney** [comment] 2018-12-12 01:21
To add to this:

- `tidyr::separate()`
- `tidyr::unite()`

**Comment by romainfrancois** [comment] 2018-12-14 11:36
- `dplyr::bind_cols()` https://github.com/tidyverse/dplyr/issues/3772

**Comment by hadley** [comment] 2023-07-20 20:27
Duplicate of #101

**Closed by hadley** 2023-07-20 20:27 UTC
